### ISSUE TITLE
V1 TODO

### ISSUE THREAD

**Issue by zachsa** [SAEON/national-climate-change-systems#1]
- [x] Upload completed Excel template
- [x] Parse single project from Excel template
- [x] Migrate old database to new database
- [ ] ControlledVocabulary dropdown lists should reflect the order that vocabulary is inserted into the database
- [x] Search page needs lots of work
- [x] Downloading projects should work

+/- Other numerous bugs and fixes
